<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-43J3MGE8" failures="1" tests="4" name="Test" time="18.662" errors="0" timestamp="2023-02-17T18:49:44 IST">
  <testcase classname="com.testLayer.LoginPageTest2" name="verifyLogin" time="0.328"/>
  <testcase classname="com.testLayer.LoginPageTest2" name="verifyLogin" time="0.275">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at com.testLayer.LoginPageTest2.verifyLogin(LoginPageTest2.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <testcase classname="com.testLayer.LoginPageTest2" name="verifyLogin" time="0.496"/>
  <testcase classname="com.testLayer.LoginPageTest2" name="verifyLogin" time="5.427"/>
</testsuite> <!-- Test -->
